# Generated by Django 2.0.1 on 2018-03-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0025_project_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.IntegerField(choices=[(1, '申请权限'), (2, '新建用户'), (3, '执行SQL')], help_text='申请类型 1 申请权限 2 新建用户 3 执行 SQL', verbose_name='申请类型')),
                ('application_content', models.CharField(help_text='申请说明', max_length=80, verbose_name='申请说明')),
                ('execute_sql', models.TextField(default='', help_text='执行 SQL', verbose_name='执行SQL')),
                ('execute_result', models.TextField(default='', help_text='执行结果', verbose_name='执行结果')),
                ('application_time', models.DateTimeField(auto_now_add=True, help_text='申请时间', verbose_name='申请时间')),
                ('execute_time', models.DateTimeField(help_text='执行时间', null=True, verbose_name='执行时间')),
                ('finished_time', models.DateTimeField(help_text='完成时间', null=True, verbose_name='完成时间')),
                ('application_status', models.IntegerField(choices=[(0, '驳回'), (1, '待审批'), (2, '项目经理审批通过'), (3, '运维经理审批通过'), (4, '已执行')], default=1, help_text=' 0 驳回 1 待审批 2 项目经理审批通过 3 运维经理审批通过 4 已执行', verbose_name='状态')),
                ('reback_reason', models.TextField(default='', help_text='驳回意见', verbose_name='驳回意见')),
                ('is_delete', models.IntegerField(default=0, help_text='0 未删除 1 已删除', verbose_name='是否删除')),
                ('appliant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='更新内容', max_length=2000, verbose_name='更新内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Application', verbose_name='application ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(help_text='db type', max_length=20, verbose_name='数据库')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.IntegerField(help_text='服务器IP 地址，转为数值型存储', verbose_name='服务器IP')),
                ('instance_name', models.CharField(help_text='实例名', max_length=20, verbose_name='实例名')),
                ('instance_env', models.IntegerField(choices=[(1, '生产环境'), (2, '测试环境'), (3, '开发环境')], help_text='1 生产环境 2 测试环境 3 开发环境', verbose_name='所属环境')),
                ('instance_username', models.CharField(help_text='数据库用户', max_length=20, verbose_name='用户')),
                ('instance_password', models.CharField(help_text='数据库密码', max_length=100, verbose_name='用户密码')),
                ('instance_port', models.IntegerField(help_text='实例端口', verbose_name='实例端口')),
                ('instance_role', models.CharField(help_text='实例角色：主、从、主/从', max_length=10, null=True, verbose_name='实例角色')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('is_delete', models.IntegerField(default=0, help_text='0 未删除 1 已删除', verbose_name='是否删除')),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Category', verbose_name='数据库类型：MySQL, SQL SERVER, MongoDB 等等 ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='更新内容', max_length=2000, verbose_name='更新内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Instance', verbose_name='instance ID')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_host', models.IntegerField(help_text='主库地址', verbose_name='主库IP')),
                ('master_port', models.IntegerField(help_text='主库端口', verbose_name='主库端口')),
                ('slave_type', models.IntegerField(help_text='从库类型：实时从库，延时从库', verbose_name='从库类型')),
                ('slave_delay', models.IntegerField(help_text='从库类型：实时从库，延时从库', verbose_name='从库延迟')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(help_text='更新时间', null=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Instance', verbose_name='实例')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Instance', verbose_name='实例ID'),
        ),
        migrations.AddField(
            model_name='application',
            name='ops_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_manager_id', to=settings.AUTH_USER_MODEL, verbose_name='运维经理'),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project', verbose_name='项目'),
        ),
    ]
