# Generated by Django 2.0.1 on 2018-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancelog',
            name='content',
            field=models.TextField(default='', help_text='更新内容', verbose_name='更新内容'),
        ),
    ]
