# Generated by Django 2.0.1 on 2018-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180320_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reback_reason',
            field=models.CharField(default='', help_text='驳回意见', max_length=200, verbose_name='驳回意见'),
        ),
    ]
