# Generated by Django 2.0.1 on 2018-03-27 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180320_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_review_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='最后校验时间', verbose_name='最后校验时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='review_result',
            field=models.TextField(default='', help_text='校验结果', verbose_name='校验结果'),
        ),
    ]
