# Generated by Django 2.0.1 on 2018-03-30 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_auto_20180327_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='ops_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='运维人员'),
            preserve_default=False,
        ),
    ]
