# Generated by Django 2.0.1 on 2018-03-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0006_instance_ops_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ops_manager',
        ),
        migrations.AddField(
            model_name='application',
            name='ops_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ops_manager_id', to=settings.AUTH_USER_MODEL, verbose_name='运维DBA'),
            preserve_default=False,
        ),
    ]
