# Generated by Django 2.0.1 on 2018-03-26 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsid', models.CharField(max_length=32, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('email', models.EmailField(default='', max_length=254, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='邮箱')),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '已受理'), (3, '已处理')], verbose_name='状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('a_time', models.DateTimeField(null=True, verbose_name='受理时间')),
                ('f_time', models.DateTimeField(null=True, verbose_name='处理时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['wsid'],
            },
        ),
    ]
