# Generated by Django 2.0.1 on 2018-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='submitter',
            field=models.CharField(default='', max_length=32, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='submitter_email',
            field=models.CharField(default='', max_length=128, verbose_name='提交人邮箱'),
        ),
    ]
