# Generated by Django 2.0.1 on 2018-03-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0002_auto_20180327_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='receive_pepole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_pepole', to=settings.AUTH_USER_MODEL, verbose_name='受理人'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
    ]
