# Generated by Django 2.0.1 on 2018-03-28 10:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0003_auto_20180327_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='have_power_change',
            field=models.BooleanField(default=False, verbose_name='是否为权限变更'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='抄送邮箱'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '未受理'), (2, '待处理'), (3, '已处理')], verbose_name='状态'),
        ),
    ]
