# Generated by Django 2.0.1 on 2018-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserapplyflow',
            name='remarks',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
    ]
