# Generated by Django 2.0.1 on 2018-02-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_authoritygroupchangelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritygroupchangelogs',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.authority_group', verbose_name='组'),
        ),
    ]
