# Generated by Django 2.0.1 on 2018-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_authoritygroupchangelogs_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_user',
            name='is_active',
            field=models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='是否启用'),
        ),
    ]
