# Generated by Django 2.0.1 on 2018-02-25 11:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20180224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_releaseflow',
            name='testingreport',
            field=tinymce.models.HTMLField(max_length=2000, verbose_name='测试报告'),
        ),
    ]
