# Generated by Django 2.0.1 on 2018-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20180225_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_releaseflow',
            name='testingreport',
            field=models.CharField(max_length=2000, verbose_name='测试报告'),
        ),
    ]
