# Generated by Django 2.0.1 on 2018-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_workflowimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority_flow',
            name='describe',
            field=models.CharField(max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project_releaseflow',
            name='testingreport',
            field=models.CharField(max_length=5000, verbose_name='测试报告'),
        ),
    ]
