# Generated by Django 2.0.1 on 2018-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20180226_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_releaseflow',
            name='testingreport',
            field=models.TextField(verbose_name='测试报告'),
        ),
    ]
