# Generated by Django 2.0.1 on 2018-02-27 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0012_auto_20180226_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('cronflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cronflow', verbose_name='计划任务申请工作流ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'workflow_cron_apply_comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project', verbose_name='项目ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'workflow_project_apply_comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('project_userflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project_userflow', verbose_name='项目成员申请工作流ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'workflow_project_member_apply_comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectReleaseApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('project_releaseflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project_releaseflow', verbose_name='项目变更申请工作流ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'workflow_project_release_apply_comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectUserApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('user_apply_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ProjectUserApplyFlow', verbose_name='项目用户申请工作流ID')),
            ],
            options={
                'db_table': 'workflow_project_user_apply_comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectUserAuthorityApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('authority_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.authority_flow', verbose_name='项目用户权限申请工作流ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'workflow_project_user_authority_apply_comment',
            },
        ),
    ]
