# Generated by Django 2.0.1 on 2018-02-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20180227_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority_flow',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='projectuserapplyflow',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Department', verbose_name='部门'),
        ),
    ]
