# Generated by Django 2.0.1 on 2018-02-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20180227_1742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authority_flow',
            unique_together=set(),
        ),
    ]
