# Generated by Django 2.0.1 on 2018-02-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20180227_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project_userflow',
            name='describe',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='projectuserapplyflow',
            name='remarks',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
    ]
