# Generated by Django 2.0.1 on 2018-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20180228_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_releaseflow',
            name='describe',
            field=models.TextField(verbose_name='发布内容'),
        ),
    ]
