# Generated by Django 2.0.1 on 2018-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20180228_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completiontime',
        ),
        migrations.AddField(
            model_name='project',
            name='approvaltime',
            field=models.DateTimeField(null=True, verbose_name='完成时间'),
        ),
    ]
