# Generated by Django 2.0.1 on 2018-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20180302_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_userflow',
            name='completiontime',
        ),
        migrations.AddField(
            model_name='project_userflow',
            name='execute_time',
            field=models.DateTimeField(null=True, verbose_name='执行时间'),
        ),
    ]
