# Generated by Django 2.0.1 on 2018-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20180302_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_releaseflow',
            name='completiontime',
        ),
        migrations.AddField(
            model_name='project_releaseflow',
            name='release_time',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
    ]
