# Generated by Django 2.0.1 on 2018-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20180302_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronflow',
            name='completiontime',
        ),
        migrations.AddField(
            model_name='cronflow',
            name='execute_time',
            field=models.DateTimeField(null=True, verbose_name='执行'),
        ),
    ]
