# Generated by Django 2.0.1 on 2018-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20180302_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_english',
            field=models.CharField(max_length=50, null=True, verbose_name='项目英文名'),
        ),
    ]
