# Generated by Django 2.0.1 on 2018-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_project_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
