# Generated by Django 2.0.1 on 2018-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_project_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserapplyflow',
            name='user_group',
            field=models.CharField(max_length=5000, null=True, verbose_name='分配组'),
        ),
    ]
