# Generated by Django 2.0.1 on 2018-03-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20180307_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronflow',
            name='status',
            field=models.IntegerField(choices=[(0, '不通过'), (1, '待审批'), (2, '待执行'), (9, '已执行添加')], help_text='0 不通过, 1 待审批, 2 待执行, 3 已执行添加', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project_releaseflow',
            name='status',
            field=models.IntegerField(choices=[(0, '不通过'), (1, '待审批'), (2, '测试审批通过'), (3, '项目经理审批通过'), (4, '待发布'), (9, '已发布')], verbose_name='状态'),
        ),
    ]
