# Generated by Django 2.0.1 on 2018-03-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_auto_20180308_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='组成员'),
        ),
    ]
