# Generated by Django 2.0.1 on 2018-03-08 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20180308_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='组成员'),
        ),
    ]
