# Generated by Django 2.0.1 on 2018-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20180308_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '不通过'), (1, '未审批'), (2, '项目经理审批通过'), (3, 'CTO审批通过'), (4, '采购审批通过'), (5, '财务审批通过'), (9, '执行中')], verbose_name='状态'),
        ),
    ]
