# Generated by Django 2.0.1 on 2018-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_auto_20180309_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserapplyflow',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='projectuserapplyflow',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approvaltime',
            field=models.DateTimeField(null=True, verbose_name='审批完成时间'),
        ),
    ]
