# Generated by Django 2.0 on 2018-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_auto_20180310_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='projectapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='projectmemberapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='projectreleaseapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='projectuserapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='projectuserauthorityapplycomment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
