# Generated by Django 2.0 on 2018-03-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_auto_20180314_2153'),
        ('workflow', '0041_auto_20180315_0927'),
    ]

    operations = [
    ]
