# Generated by Django 2.0.1 on 2018-03-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('workflow', '0043_auto_20180318_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_group',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='成员类型'),
        ),
        migrations.AlterField(
            model_name='authority_flow',
            name='describe',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='cronflow',
            name='describe',
            field=models.TextField(verbose_name='描述'),
        ),
    ]
