# Generated by Django 2.0.1 on 2018-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_auto_20180319_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('depart_name', 'project')},
        ),
    ]
