# Generated by Django 2.0.1 on 2018-03-21 11:21

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0045_auto_20180320_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_releaseflow',
            name='type',
            field=models.CharField(default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='类型'),
        ),
    ]
