# Generated by Django 2.0.1 on 2018-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0047_project_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='have_parent_project',
            field=models.BooleanField(default=False, verbose_name='是否有父项目'),
        ),
    ]
