# Generated by Django 2.0.1 on 2018-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0048_project_have_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_releaseflow',
            name='enclosure',
            field=models.FilePathField(blank=True, null=True, path='E:\\Django测试项目\\new_devops\\static/upload\\test_report_enclosure', recursive=True),
        ),
    ]
