# Generated by Django 2.0.1 on 2018-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_id', models.CharField(help_text='SupportID', max_length=20, verbose_name='云平台账号id')),
                ('instance_id', models.CharField(help_text='InstanceID', max_length=50, verbose_name='实例id')),
                ('instance_type', models.CharField(help_text='InstanceType', max_length=50, verbose_name='实例类型')),
                ('instance_class', models.CharField(help_text='InstanceClass', max_length=100, verbose_name='实例类别')),
                ('engine', models.CharField(help_text='Engine', max_length=100, verbose_name='引擎')),
                ('engine_version', models.CharField(help_text='EngineVersion', max_length=100, verbose_name='引擎版本')),
                ('region_id', models.CharField(help_text='RegionId', max_length=100, verbose_name='实例region')),
                ('instance_description', models.CharField(help_text='InstanceDesc', max_length=100, verbose_name='实例描述')),
                ('create_time', models.DateTimeField(help_text='create_time', verbose_name='创建时间')),
                ('expire_time', models.DateTimeField(help_text='expire_time', verbose_name='创建时间')),
                ('instance_status', models.CharField(help_text='instance_status', max_length=20, verbose_name='实例状态')),
            ],
        ),
    ]
