# Generated by Django 2.0.1 on 2018-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCloudServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50, verbose_name='实例名 *')),
                ('cloud_type', models.CharField(max_length=50, null=True, verbose_name='云类型')),
                ('host_account', models.CharField(max_length=50, null=True, verbose_name='主机账号')),
                ('host_password', models.CharField(max_length=1024, null=True, verbose_name='主机密码')),
                ('create_date', models.DateField(null=True, verbose_name='创建时间')),
                ('physical_host_ip', models.GenericIPAddressField(null=True, verbose_name='宿主机IP')),
                ('physical_host_account', models.CharField(max_length=50, null=True, verbose_name='宿主机账号')),
                ('physical_host_password', models.CharField(max_length=1024, null=True, verbose_name='宿主机密码')),
                ('contact_people', models.CharField(max_length=50, verbose_name='对接人 *')),
                ('project_group', models.CharField(max_length=50, null=True, verbose_name='项目组')),
                ('cpu_number', models.IntegerField(verbose_name='CPU核数 *')),
                ('memory_number', models.IntegerField(verbose_name='内存 *')),
                ('ext_ip', models.GenericIPAddressField(null=True, verbose_name='公网IP')),
                ('int_ip', models.GenericIPAddressField(verbose_name='内网IP *')),
                ('os', models.CharField(max_length=50, null=True, verbose_name='操作系统')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='主机名')),
                ('disk_size', models.CharField(max_length=50, null=True, verbose_name='磁盘空间')),
                ('bandwidth', models.CharField(max_length=50, null=True, verbose_name='带宽')),
                ('status', models.IntegerField(choices=[(1, '运行中'), (0, '已停止'), (2, '维护中'), (3, '已过期'), (4, '未使用')], default=1, verbose_name='状态 *')),
                ('describe', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmdb_private_cloud_server',
            },
        ),
        migrations.CreateModel(
            name='PublicCouldServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50, verbose_name='实例名 *')),
                ('platform', models.CharField(max_length=50, null=True, verbose_name='所在平台')),
                ('platform_account', models.CharField(max_length=50, verbose_name='平台账号 *')),
                ('platform_password', models.CharField(max_length=1024, null=True, verbose_name='平台密码')),
                ('host_account', models.CharField(max_length=50, null=True, verbose_name='主机账号')),
                ('host_password', models.CharField(max_length=1024, null=True, verbose_name='主机密码')),
                ('create_date', models.DateField(null=True, verbose_name='创建时间')),
                ('expire_date', models.DateField(verbose_name='到期时间 *')),
                ('applicant', models.CharField(max_length=50, verbose_name='申请人 *')),
                ('project_group', models.CharField(max_length=50, null=True, verbose_name='项目组')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='所在区域')),
                ('contact_people', models.CharField(max_length=50, verbose_name='对接人 *')),
                ('cpu_number', models.IntegerField(verbose_name='CPU核数 *')),
                ('memory_number', models.IntegerField(verbose_name='内存 *')),
                ('ext_ip', models.GenericIPAddressField(verbose_name='公网IP *')),
                ('int_ip', models.GenericIPAddressField(null=True, verbose_name='内网IP')),
                ('os', models.CharField(max_length=50, null=True, verbose_name='操作系统')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='主机名')),
                ('disk_size', models.CharField(max_length=50, null=True, verbose_name='磁盘空间')),
                ('bandwidth', models.CharField(max_length=50, null=True, verbose_name='带宽')),
                ('status', models.IntegerField(choices=[(1, '运行中'), (0, '已停止'), (2, '维护中'), (3, '已过期'), (4, '未使用')], default=1, verbose_name='状态 *')),
                ('describe', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmdb_public_cloud_server',
            },
        ),
    ]
