# Generated by Django 2.0.1 on 2018-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_privatecloudserver_publiccouldserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_place', models.CharField(max_length=50, verbose_name='IDC位置 *')),
                ('rack_code', models.CharField(max_length=50, verbose_name='机架编码 *')),
                ('rack_number', models.CharField(max_length=50, verbose_name='机架号 *')),
                ('device_info', models.CharField(max_length=50, verbose_name='设备信息 *')),
                ('asset_brand', models.CharField(max_length=50, null=True, verbose_name='品牌')),
                ('asset_model_number', models.CharField(max_length=50, null=True, verbose_name='型号')),
                ('use_date', models.DateField(null=True, verbose_name='上架日期')),
                ('responsible', models.CharField(max_length=50, verbose_name='责任人 *')),
                ('project_group', models.CharField(max_length=50, null=True, verbose_name='所属项目')),
                ('cpu_model_number', models.CharField(max_length=50, null=True, verbose_name='CPU型号')),
                ('cpu_kernel_num', models.IntegerField(null=True, verbose_name='CPU核数')),
                ('memory_model_number', models.CharField(max_length=50, null=True, verbose_name='内存型号')),
                ('memory_size', models.IntegerField(null=True, verbose_name='内存容量')),
                ('ext_ip', models.GenericIPAddressField(null=True, verbose_name='公网IP')),
                ('int_ip', models.GenericIPAddressField(null=True, verbose_name='内网IP')),
                ('os_version', models.CharField(max_length=50, null=True, verbose_name='OS版本')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='主机名')),
                ('disk_number', models.IntegerField(null=True, verbose_name='磁盘个数')),
                ('disk_size', models.CharField(max_length=50, null=True, verbose_name='磁盘容量')),
                ('raid_type', models.CharField(max_length=50, null=True, verbose_name='raid类型')),
                ('status', models.IntegerField(choices=[(1, '已上线'), (0, '已下线'), (2, '维修中'), (3, '已入库'), (4, '未使用')], default=1, verbose_name='状态 *')),
                ('server_room_temper', models.CharField(max_length=50, null=True, verbose_name='机房温度')),
                ('server_room_humidity', models.CharField(max_length=50, null=True, verbose_name='机房湿度')),
                ('power_system', models.CharField(max_length=50, null=True, verbose_name='电力系统')),
                ('bandwidth', models.CharField(max_length=50, null=True, verbose_name='出口带宽')),
                ('describe', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmdb_idc',
            },
        ),
    ]
