# Generated by Django 2.0.1 on 2018-02-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_cronapplycomment_projectapplycomment_projectmemberapplycomment_projectreleaseapplycomment_projectuse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercenter', '0003_auto_20180225_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('depart_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.project', verbose_name='项目')),
            ],
        ),
    ]
