# Generated by Django 2.0.1 on 2018-03-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0010_auto_20180305_1709'),
        ('usercenter', '0008_auto_20180306_0938'),
    ]

    operations = [
    ]
