# Generated by Django 2.0 on 2018-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0015_auto_20180308_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_url', models.CharField(max_length=100, verbose_name='模块url')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
            ],
        ),
    ]
