# Generated by Django 2.0.1 on 2018-03-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0016_systemmodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmodule',
            options={'verbose_name': '平台菜单模块', 'verbose_name_plural': '平台菜单模块'},
        ),
    ]
